# Generated by Django 5.2.7 on 2025-10-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='finalizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
