# Generated by Django 5.2.7 on 2025-11-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_add_observacao_pedido'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['tipo', 'produto', 'criado_em'], name='pedidos_mov_tipo_c693cf_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentoestoque',
            index=models.Index(fields=['pedido'], name='pedidos_mov_pedido__7acbcc_idx'),
        ),
    ]
