# Generated by Django 5.2.7 on 2025-11-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_movimentoestoque_pedidos_mov_tipo_c693cf_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('RASC', 'Rascunho'), ('AGPG', 'Aguardando Pagamento'), ('ENVC', 'Enviado à Cozinha'), ('CONC', 'Concluído'), ('CANC', 'Cancelado')], default='RASC', max_length=4),
        ),
    ]
